# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: NeoVim tests
on: [push]
jobs:
  plenary-tests:
    runs-on: ubuntu-latest
    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}/.config/
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.11.0
          arch: 'x86_64'
      - run: make test
